name: Daily Gold Tracker Run

on:
  schedule:
    - cron: '0 18 * * *'  # Runs daily at 21:00 UTC (9 PM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-gold-tracker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Run gold tracker script
      env:
        API_NINJAS_KEY: ${{ secrets.API_NINJAS_KEY }}
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python gold_tracker.py